version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cityfix-postgres
    ports:
      - "${POSTGRES_LOCAL_PORT}:5432" # Puerto estándar de Postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cityfix-network
    restart: always

  api:
    build: .
    container_name: cityfix-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - cityfix-network
    restart: always

volumes:
  postgres_data:

networks:
  cityfix-network:
    driver: bridge