# --- PROD SAFE DEFAULTS ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.sql.init.mode=never

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

logging.level.org.springdoc=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.web.FilterChainProxy=INFO
logging.level.org.springframework.web=INFO

management.endpoint.health.show-details=never
